# Generated by Django 5.0.3 on 2024-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='qwerty', max_length=20),
            preserve_default=False,
        ),
    ]
